SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A6969B83BA5836B}" {
   m_sIdentifier "Illegal"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A6969B8383F4B52}" {
     m_sEntityPrefab "{850B60FDE623798B}Prefabs/Items/GW_CannabisTop_Indica.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A8237246B3B}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B83F90E8CF}" {
     m_sEntityPrefab "{93FC2ED987828363}Prefabs/Items/GW_CannabisTop_Sativa.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A822AE5367B}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B83EC8FBD3}" {
     m_sEntityPrefab "{776EA4A47C011B5E}Prefabs/Items/GW_PotItem_Empty.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A8221B92B42}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B83E595060}" {
     m_sEntityPrefab "{0D934946BE982287}Prefabs/Items/GW_SeedsIndica.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A82194A268D}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B83DB08842}" {
     m_sEntityPrefab "{72FF76B6070C3F65}Prefabs/Items/GW_SeedsSativa.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A8208D31B73}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}