JWK_ShopInventoryConfig {
 m_aItemGroups {
  JWK_ShopInventoryItemGroupConfig "{64B3187A670B57B0}" : "{03B98B50F7F44E41}Configs/Shops/ItemGroups/PlayerWeapons.conf" {
  }
  JWK_ShopInventoryItemGroupConfig "{6A5B0CCF54F3D956}" {
   m_aPrefabs {
    "{BA4866B5E0270FAA}Prefabs/Items/Medicine/JWK_EpinephrineInjection.et"
    "{50C1EC3C627018CE}Prefabs/Items/Lockpicks/Lockpick_base.et"
   }
  }
  JWK_ShopInventoryItemGroupConfig "{6A5AF1436F910300}" {
   m_aEntityCatalogImports {
    JWK_EntityCatalogShopFilterRule "{6A5AF1436F910301}" {
     m_iCatalogType INVENTORY_ITEM
     m_bRequireArsenalItem 0
     m_aPrefabNameFilters {
      JWK_BaseResourceNameFilter "{6A5AF1436F910302}" {
       m_sPrefabNameIncludeFilter {
        "*GW_PotItem*"
        "*GW_CannabisTop*"
       }
      }
     }
    }
   }
   m_aPrefabs {
    "{981467EA808096D4}Prefabs/Props/GW_PotItem.et"
    "{6A5AF1436F910600}Prefabs/Modded/Items/GW_CannabisTop.et"
   }
  }
 }
}