JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{6A5AF1436F910100}" {
   m_sTitle "Growing Weed - Pot plant"
   m_aPrefabs {
    "{981467EA808096D4}Prefabs/Props/GW_PotItem.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{6A5AF1436F910101}" {
    m_iMoneyPrice 1000
    m_iSuppliesPrice 0
   }
  }
  JWK_ItemAttributesConfigRule "{6A5AF1436F910102}" {
   m_sTitle "Growing Weed - Weed tops (harvested)"
   m_aPrefabs {
    "{6A5AF1436F910600}Prefabs/Modded/Items/GW_CannabisTop.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{6A5AF1436F910103}" {
    m_iMoneyPrice 80
    m_iSuppliesPrice 0
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{6A5AF1436F910200}" {
   m_aTargetFactionRoles {
    SUPPORTING
   }
   m_aAddItems {
    "{981467EA808096D4}Prefabs/Props/GW_PotItem.et"
    "{6A5AF1436F910600}Prefabs/Modded/Items/GW_CannabisTop.et"
   }
  }
 }
}
