SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A6969B81B57D59C}" {
   m_sIdentifier "Illegal"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A6969B81F2F39DA}" {
     m_sEntityPrefab "{850B60FDE623798B}Prefabs/Items/GW_CannabisTop_Indica.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A82EF57EB84}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B81E64918C}" {
     m_sEntityPrefab "{93FC2ED987828363}Prefabs/Items/GW_CannabisTop_Sativa.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A82F706B067}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B81D926FDC}" {
     m_sEntityPrefab "{776EA4A47C011B5E}Prefabs/Items/GW_PotItem_Empty.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A82FDE83B97}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 100
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B81CCC0AB7}" {
     m_sEntityPrefab "{0D934946BE982287}Prefabs/Items/GW_SeedsIndica.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A82FBEEA674}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B813B9B67E}" {
     m_sEntityPrefab "{72FF76B6070C3F65}Prefabs/Items/GW_SeedsSativa.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A8200B4C1AA}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}