SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A6969B806A19966}" {
   m_sIdentifier "Illegal"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A6969B8FB473359}" {
     m_sEntityPrefab "{850B60FDE623798B}Prefabs/Items/GW_CannabisTop_Indica.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A8252C83D5C}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B8FABF41BF}" {
     m_sEntityPrefab "{93FC2ED987828363}Prefabs/Items/GW_CannabisTop_Sativa.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A825470D71B}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B8F99704DC}" {
     m_sEntityPrefab "{776EA4A47C011B5E}Prefabs/Items/GW_PotItem_Empty.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A824DD2684F}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B8F883A30B}" {
     m_sEntityPrefab "{0D934946BE982287}Prefabs/Items/GW_SeedsIndica.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A82450405A7}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A6969B8E84B5509}" {
     m_sEntityPrefab "{72FF76B6070C3F65}Prefabs/Items/GW_SeedsSativa.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A6A1A823F3C32F8}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}